project:
  type: website

website:
  title: "andrewghazi.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/andrewGhazi

format:
  html:
    theme: darkly
    css: styles.css



